# Site settings
title: Anas Mohamed
email: anasmohamed786@outlook.com
description: Blog about me and the advancements I am making
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://am1205.github.io/" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
instagram_url: https://www.instagram.com/anas.m18/?hl=en
linkedin_url: https://www.linkedin.com/in/anas-mohamed-550049224/
twitter_url: https://twitter.com/szechuan__

# Build settings
markdown: kramdown
